name: Continuous Integration

on: [push, pull_request]

jobs:
  build-jar:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Build Effekt compiler and run tests
    runs-on: ${{ matrix.os }}
    env:
      EFFEKT_LLVM_VERSION: 15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Chez Scheme
      run: sudo apt-get install chezscheme

    - name: Install latest LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Run tests
      run: sbt clean test

    - name: Assemble fully optimized js file
      run: sbt effektJS/fullOptJS

    - name: Try installing effekt binary
      run: sbt install

    - name: Run effekt binary
      run: effekt --help
